# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieHunter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieHunter
pod 'Firebase/Core'
pod 'FirebaseAuth'
pod 'Firebase/Auth'
pod 'FirebaseStorage'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'FirebaseDatabase'
end
